// flow-typed signature: 31c90be46808703413a2f7b4d331d3e9
// flow-typed version: <<STUB>>/lodash.curry_v^4.1.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.curry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.curry' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.curry/index' {
    declare module.exports: $Exports<'lodash.curry'>;
}
declare module 'lodash.curry/index.js' {
    declare module.exports: $Exports<'lodash.curry'>;
}
